namespace TaxFiling.Web.Models
{
    public class UserTransactions
    {
        public int OrderId { get; set; } // Auto-generated by DB
        public string OrderNumber { get; set; }
        public string UserId { get; set; }
        public int? PackageId { get; set; }
        public decimal? TransactionAmount { get; set; }
        public int? TransactionStatus { get; set; }
        public string Currency { get; set; }
        public DateTime? TransactionCreatedDate { get; set; }
        public string OnePayTransactionId { get; set; }
        public string OnePayTransactionRequestDatetime { get; set; }
        public bool? OnePayStatus { get; set; }
        public string OnePayPaidOn { get; set; }
    }
}
